---
- name: Converge Negative tests for 'eos_designs_facts' - missing-cv-topology-default-mlag-interfaces-peer1
  hosts: missing-cv-topology-default-mlag-interfaces-peer1
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-cv-topology-default-uplink-interfaces
  hosts: missing-cv-topology-default-uplink-interfaces
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-cv-topology
  hosts: missing-cv-topology
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-loopback-ipv4-pool
  hosts: missing-loopback-ipv4-pool
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-vtep-loopback-ipv4-pool
  hosts: missing-vtep-loopback-ipv4-pool
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-mlag-peer
  hosts: missing-mlag-peer
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - mlag_odd_id_oddodd1
  hosts: mlag_odd_id_oddodd1
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-mlag-peer-ipv4-pool
  hosts: missing-mlag-peer-ipv4-pool1
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-mlag-peer-ipv6-pool
  hosts: missing-mlag-peer-ipv6-pool1
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-mlag-peer-l3-ipv4-pool
  hosts: missing-mlag-peer-l3-ipv4-pool1
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-mlag-interfaces1
  hosts: missing-mlag-interfaces1
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-id-for-mlag1
  hosts: missing-id-for-mlag1
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - missing-id-for-secondary-mlag2
  hosts: missing-id-for-secondary-mlag2
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts' - invalid-schema
  hosts: invalid-schema
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: invalid-schema-connected-endpoints
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_INVALID_UPLINK_PORT_CHANNEL_ID_1
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_INVALID_UPLINK_PORT_CHANNEL_ID_2
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_INVALID_UPLINK_PORT_CHANNEL_ID_3
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_P2P_VRFS
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_DOWNLINK_POOLS_DUPLICATE
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_DOWNLINK_POOLS_MISSING
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FAILURE_CONNECTED_ENDPOINT_PORT_PROFILE_DOES_NOT_EXIST_IN_FACTS
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: MISSING_BGP_AS_WITH_L3_INTERFACES_BGP_PEERS
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_ID_STATIC_AND_POOL_MANAGER_INVALID
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_ID_STATIC_AND_POOL_MANAGER_COLLISION
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          run_once: true
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FABRIC_UNDEFINED_PEER
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: EOS_DESIGNS_FAILURES_INCLUDED
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: inband-mgmt-missing-id-with-subnet
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: inband-mgmt-missing-id-with-ipv6-subnet
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: SMALL_BGP_AS_RANGE
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: missing-router-id-pool
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: missing-vtep-loopback-ipv6-pool
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: missing-mlag-peer-l3-ipv6-pool
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: unsupported-wan-router-underlay-ipv6-numbered
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: unsupported-underlay-multicast-underlay-ipv6-numbered
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: unsupported-rfc5549-underlay-ipv6-numbered
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: unsupported-vtep-vvtep-ip-underlay-ipv6-numbered
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: unsupported-inband-ztp-ip-underlay-ipv6-numbered
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: unsupported-non-ebgp-underlay-routing-protocol-ip-underlay-ipv6-numbered
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: missing-wan-interfaces
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: missing-wan-carriers
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: missing-wan-interfaces-ip-address
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_structured_config'
  hosts: wan-server-with-interfaces-as-dhcp-address
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

- name: Converge Negative tests for 'eos_designs_facts'
  hosts: FAILURE_OVERLAY_ROUTING_PROTOCOL_ADDRESS_FAMILY_IPV6
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_designs
      rescue:
        - name: Assert eos_designs failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message
